title: DiSk++
description: A C++ library for the rapid prototyping of Discontinuous Skeletal methods
theme: just-the-docs

url: https://wareHHOuse.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
